apiVersion: v1
kind: Service
metadata:
  name: transaction-management-service
  labels:
    app: transaction-management
spec:
  type: LoadBalancer
  selector:
    app: transaction-management
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000